version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=1224
      - MYSQL_DATABASE=open_store_db
      - TZ=Asia/Tashkent 
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - app-network

  app:
    build: .
    container_name: openstore_app
    ports:
      - "8083:8083"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/open_store_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Tashkent
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=1224
      - SPRING_MAIL_HOST=smtp.gmail.com
      - SPRING_MAIL_PORT=587
      - SPRING_MAIL_USERNAME=abdugafforkabiljanov@gmail.com
      - SPRING_MAIL_PASSWORD=
      - APP_IMAGE_UPLOAD_DIR=/images
      - TZ=Asia/Tashkent 
    volumes:
      - ./images:/images
      - ./src/main/resources/templates:/app/templates 
      - ./src/main/resources/static:/app/static 
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
