#spring:
#  application:
#    name: open-store
#
#  web:
#    resources:
#      static-locations: file:images/
#
#  datasource:
##    url: jdbc:mysql://localhost:3306/open_store_db
#    url: jdbc:mysql://mysql:3306/open_store_db
#    username: root
#    password: 1224
#    driver-class-name: com.mysql.cj.jdbc.Driver
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    open-in-view: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect
#
#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username: abdugafforkabiljanov@gmail.com
#    password:
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true
#          connection timeout: 5000
#          timeout: 5000
#          write timeout: 5000
#
#  security:
#    user:
#      name: none
#      password: none
#
#server:
#  port: 8083
#  servlet:
#    session:
#      timeout: 30m
#
#image:
#  upload:
#    dir: images
#
#logging:
#  level:
#    org.springframework.web: DEBUG
#    org.springframework.security: TRACE
#    org.springframework.mail: DEBUG
#    ru.gb: TRACE
#    org.hibernate.SQL: DEBUG
#    org.hibernate.type: TRACE
#
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"
spring:
  application:
    name: open-store

  web:
    resources:
      static-locations: file:images/

  datasource:
    url: jdbc:mysql://mysql:3306/open_store_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: 1224
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect # MySQL8Dialect o‘rniga MySQLDialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: abdugafforkabiljanov@gmail.com
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

  security:
    user:
      name: none
      password: none

server:
  port: 8083
  servlet:
    session:
      timeout: 30m

image:
  upload:
    dir: images

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.security: TRACE
    org.springframework.mail: DEBUG
    ru.gb: TRACE
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE

management:
  endpoints:
    web:
      exposure:
        include: "*"